### ISSUE TITLE
concurrent package builds in same directory fails

### ISSUE THREAD

**Issue by thomasf** [cbednarski/mkdeb#11]
- the TempPath option isn't being used
- no temporary directory is used at all

I haven't looked at the details of the deb file creation so I might have missed
something but it seems like the whole process just use io.writer's writing
directly to the .deb-archive instead of writing it out to multiple files first?

new suggestion: create intermediate files concurrently in goroutines

**Comment by cbednarski** [comment]
Thanks for the PRs! I am not getting emails from GitHub for some reason so I just saw all three of them; I'll look them over this weekend.

> new suggestion: create intermediate files concurrently in goroutines

Sounds like a good change to me! I think when I first wrote this I was taking apart .ar files and it was helpful to have them on disk but it's not necessary at this point.

**Comment by thomasf** [comment]
I implemented concurrent archive writing (which was at least about 13% faster for small package builds) but it introduced some bug and it got more and more drawn into fixing related bugs so I'll defer writing improvements like that until some bugs and usage issues are resolved. 
Please review and merge/comment on my pull requests if possible
